// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnkmarduszgtybwlslrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxua21hcmR1c3pndHlid2xzbHJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODIwMTcsImV4cCI6MjA3NDA1ODAxN30.ia5zCKH49vaQ_yy-g9_VHdQlGCZuGolmTH9r4V8nuXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});